// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdngnhaxibiplkdyfoiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbmduaGF4aWJpcGxrZHlmb2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMzc2MTksImV4cCI6MjA1OTYxMzYxOX0.Ei5H9FieonbikNYIs3QT91vhF5B5ABt0FQiNGXCg89o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);